apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app # Service의 이름
spec:
  type: LoadBalancer # 외부 접근을 위한 로드 밸런서 타입
  ports:
    - port: 80 # 외부에서 접근할 포트
      targetPort: 8080 # 내부 컨테이너의 포트
  selector:
    app: spring-boot-app # 연결할 Pod의 라벨 선택자
